spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.1.138/suqinglin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xyzh2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 页面热加载
  thymeleaf:
    cache: false
# 端口号
server:
  port: 8099
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml